name: appnation_dog_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  modal_bottom_sheet: ^3.0.0-pre
  dio: ^5.3.3
  data_channel: ^2.0.0+1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  injectable: ^2.3.0
  get_it: ^7.6.4
  jovial_svg: ^1.1.17
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  very_good_analysis: ^5.0.0+1
  flutter_gen_runner: ^5.3.1


flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
